export const keyUserAuth = 'user auth'
export const keyUserGetMe = 'user getMe'
export const keyUserDataUpdate = 'user update'
export const keyUserAvatarUpdate = 'user update'

export const keyTodoCreate = 'todo create'
export const keyTodoGetOne = 'todo getOne'
export const keyTodoGetAll = 'todo getAll'
export const keyTodoUpdate = 'todo update'
export const keyTodoRemove = 'todo remove'
